#DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://ulsq0qqx999wqz84.chr7pe7iynqr.eu-west-1.rds.amazonaws.com/tv4zbvx0cg2igobq?reconnect=true?useUnicode=yes&characterEncoding=UTF-8
        username: xc2i3bfkr11mr4zr
        password: qon9z0mw29gdqgbu
        sqlScriptEncoding: UTF-8
    flyway:
        url: jdbc:mysql://ulsq0qqx999wqz84.chr7pe7iynqr.eu-west-1.rds.amazonaws.com/tv4zbvx0cg2igobq?reconnect=true?useUnicode=yes&characterEncoding=UTF-8
        user: xc2i3bfkr11mr4zr
        password: qon9z0mw29gdqgbu
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: update

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type: TRACE

server:
  port=${PORT:8080}
